package numj.bench;

/**
 * Plain-Java reference implementations on {@code double[]} (row-major for matrices).
 *
 * <ul>
 *   <li><b>naive</b>: the straightforward single-accumulator loops most Java code uses. Same per-element
 *       arithmetic as numj, but left-to-right summation, so results differ in the last bits.</li>
 *   <li><b>blocked</b>: exactly numj's summation order (4096-element blocks, 16 lanes, pairwise trees) and
 *       numj's row-normalisation rules, so results are <i>bit-identical</i> to the Fortran kernels. Used both
 *       as a test oracle and as the "best effort plain Java" benchmark baseline.</li>
 * </ul>
 * This file's 16-lane block functions are generated by a small template (see README); edit with care.
 */
public final class JavaKernels {
    static final int BLOCK = 4096;
    static final double SS_LO = 0x1p-968;

    private JavaKernels() {}

    // ------------------------------------------------------------------ naive

    public static double sqdistNaive(double[] a, double[] b) {
        double s = 0;
        for (int i = 0; i < a.length; i++) {
            double d = a[i] - b[i];
            s += d * d;
        }
        return s;
    }

    public static double sumSqMulAddNaive(double[] a, double[] b, double[] c) {
        double s = 0;
        for (int i = 0; i < a.length; i++) {
            double t = a[i] * b[i] + c[i];
            s += t * t;
        }
        return s;
    }

    public static void sqdistRowsNaive(double[] q, double[] x, int rows, int cols, double[] out) {
        for (int r = 0; r < rows; r++) {
            double s = 0;
            int o = r * cols;
            for (int j = 0; j < cols; j++) {
                double d = x[o + j] - q[j];
                s += d * d;
            }
            out[r] = s;
        }
    }

    /** Naive normalisation (zero-norm rows copied, no overflow/underflow rescaling, like NumPy). */
    public static void normalizeRowsNaive(double[] x, double[] y, int rows, int cols) {
        for (int r = 0; r < rows; r++) {
            int o = r * cols;
            double ss = 0;
            for (int j = 0; j < cols; j++) ss += x[o + j] * x[o + j];
            double nrm = Math.sqrt(ss);
            if (nrm == 0) System.arraycopy(x, o, y, o, cols);
            else for (int j = 0; j < cols; j++) y[o + j] = x[o + j] / nrm;
        }
    }

    // ------------------------------------------------------------------ blocked (numj order)

    public static double sqdistBlocked(double[] a, double[] b) {
        return sqdistBlocked(a, 0, b, 0, a.length);
    }

    public static double sqdistBlocked(double[] a, int ao, double[] b, int bo, int n) {
        if (n <= 0) return 0;
        int nb = (n + BLOCK - 1) / BLOCK;
        if (nb == 1) return blkSqdist(a, ao, b, bo, n);
        double[] p = new double[nb];
        for (int k = 0; k < nb; k++) {
            int lo = k * BLOCK;
            p[k] = blkSqdist(a, ao + lo, b, bo + lo, Math.min(BLOCK, n - lo));
        }
        return pairwise(p, nb);
    }

    public static double sumSqMulAddBlocked(double[] a, double[] b, double[] c) {
        int n = a.length;
        if (n == 0) return 0;
        int nb = (n + BLOCK - 1) / BLOCK;
        if (nb == 1) return blkSumSqMulAdd(a, 0, b, 0, c, 0, n);
        double[] p = new double[nb];
        for (int k = 0; k < nb; k++) {
            int lo = k * BLOCK;
            p[k] = blkSumSqMulAdd(a, lo, b, lo, c, lo, Math.min(BLOCK, n - lo));
        }
        return pairwise(p, nb);
    }

    static double sumSqBlocked(double[] x, int xo, int n) {
        if (n <= 0) return 0;
        int nb = (n + BLOCK - 1) / BLOCK;
        if (nb == 1) return blkSumSq(x, xo, n);
        double[] p = new double[nb];
        for (int k = 0; k < nb; k++) {
            int lo = k * BLOCK;
            p[k] = blkSumSq(x, xo + lo, Math.min(BLOCK, n - lo));
        }
        return pairwise(p, nb);
    }

    public static void sqdistRowsBlocked(double[] q, double[] x, int rows, int cols, double[] out) {
        for (int r = 0; r < rows; r++) out[r] = sqdistBlocked(x, r * cols, q, 0, cols);
    }

    /** numj's normalisation rules (see NumJ.normalizeRows), bit-identical results. norms may be null. */
    public static void normalizeRowsBlocked(double[] x, double[] y, int rows, int cols, double[] norms) {
        for (int r = 0; r < rows; r++) {
            int o = r * cols;
            double ss = sumSqBlocked(x, o, cols);
            double nrm;
            if (Double.isNaN(ss) || (ss >= SS_LO && ss <= Double.MAX_VALUE)) {
                nrm = Double.isNaN(ss) ? ss : Math.sqrt(ss);
                for (int j = 0; j < cols; j++) y[o + j] = x[o + j] / nrm;
            } else {
                double amax = 0;
                for (int j = 0; j < cols; j++) amax = Math.max(amax, Math.abs(x[o + j]));
                if (amax == 0) {
                    nrm = 0;
                    System.arraycopy(x, o, y, o, cols);
                } else if (amax > Double.MAX_VALUE) {
                    nrm = amax;
                    for (int j = 0; j < cols; j++) y[o + j] = x[o + j] / nrm;
                } else {
                    double s = 0;
                    for (int j = 0; j < cols; j++) {
                        double t = x[o + j] / amax;
                        s += t * t;
                    }
                    double rs = Math.sqrt(s);
                    nrm = amax * rs;
                    for (int j = 0; j < cols; j++) y[o + j] = (x[o + j] / amax) / rs;
                }
            }
            if (norms != null) norms[r] = nrm;
        }
    }

    // ------------------------------------------------------------------ shared pieces

    static double laneTree(double s0, double s1, double s2, double s3, double s4, double s5, double s6, double s7,
                           double s8, double s9, double s10, double s11, double s12, double s13, double s14, double s15) {
        double t0 = s0 + s8, t1 = s1 + s9, t2 = s2 + s10, t3 = s3 + s11;
        double t4 = s4 + s12, t5 = s5 + s13, t6 = s6 + s14, t7 = s7 + s15;
        t0 = t0 + t4; t1 = t1 + t5; t2 = t2 + t6; t3 = t3 + t7;
        t0 = t0 + t2; t1 = t1 + t3;
        return t0 + t1;
    }

    /** Same fixed pairwise shape as the Fortran 'pairwise' routine. Destroys p. */
    static double pairwise(double[] p, int n) {
        int len = n;
        while (len > 1) {
            int half = len / 2;
            for (int i = 0; i < half; i++) p[i] = p[2 * i] + p[2 * i + 1];
            if ((len & 1) == 1) {
                p[half] = p[len - 1];
                len = half + 1;
            } else {
                len = half;
            }
        }
        return p[0];
    }

    // ------------------------------------------------------------------ generated 16-lane blocks

    /** One block (a[ao..], b[bo..]); element j goes to lane j % 16. */
    static double blkSqdist(double[] a, int ao, double[] b, int bo, int m) {
        double s0 = 0; double s1 = 0; double s2 = 0; double s3 = 0; double s4 = 0; double s5 = 0; double s6 = 0; double s7 = 0; double s8 = 0; double s9 = 0; double s10 = 0; double s11 = 0; double s12 = 0; double s13 = 0; double s14 = 0; double s15 = 0;
        int i = 0;
        for (; i + 16 <= m; i += 16) {
            { double d = a[ao + i + 0] - b[bo + i + 0]; s0 += d * d; }
            { double d = a[ao + i + 1] - b[bo + i + 1]; s1 += d * d; }
            { double d = a[ao + i + 2] - b[bo + i + 2]; s2 += d * d; }
            { double d = a[ao + i + 3] - b[bo + i + 3]; s3 += d * d; }
            { double d = a[ao + i + 4] - b[bo + i + 4]; s4 += d * d; }
            { double d = a[ao + i + 5] - b[bo + i + 5]; s5 += d * d; }
            { double d = a[ao + i + 6] - b[bo + i + 6]; s6 += d * d; }
            { double d = a[ao + i + 7] - b[bo + i + 7]; s7 += d * d; }
            { double d = a[ao + i + 8] - b[bo + i + 8]; s8 += d * d; }
            { double d = a[ao + i + 9] - b[bo + i + 9]; s9 += d * d; }
            { double d = a[ao + i + 10] - b[bo + i + 10]; s10 += d * d; }
            { double d = a[ao + i + 11] - b[bo + i + 11]; s11 += d * d; }
            { double d = a[ao + i + 12] - b[bo + i + 12]; s12 += d * d; }
            { double d = a[ao + i + 13] - b[bo + i + 13]; s13 += d * d; }
            { double d = a[ao + i + 14] - b[bo + i + 14]; s14 += d * d; }
            { double d = a[ao + i + 15] - b[bo + i + 15]; s15 += d * d; }
        }
        int r = m - i;
        if (r > 0) { double d = a[ao + i + 0] - b[bo + i + 0]; s0 += d * d; }
        if (r > 1) { double d = a[ao + i + 1] - b[bo + i + 1]; s1 += d * d; }
        if (r > 2) { double d = a[ao + i + 2] - b[bo + i + 2]; s2 += d * d; }
        if (r > 3) { double d = a[ao + i + 3] - b[bo + i + 3]; s3 += d * d; }
        if (r > 4) { double d = a[ao + i + 4] - b[bo + i + 4]; s4 += d * d; }
        if (r > 5) { double d = a[ao + i + 5] - b[bo + i + 5]; s5 += d * d; }
        if (r > 6) { double d = a[ao + i + 6] - b[bo + i + 6]; s6 += d * d; }
        if (r > 7) { double d = a[ao + i + 7] - b[bo + i + 7]; s7 += d * d; }
        if (r > 8) { double d = a[ao + i + 8] - b[bo + i + 8]; s8 += d * d; }
        if (r > 9) { double d = a[ao + i + 9] - b[bo + i + 9]; s9 += d * d; }
        if (r > 10) { double d = a[ao + i + 10] - b[bo + i + 10]; s10 += d * d; }
        if (r > 11) { double d = a[ao + i + 11] - b[bo + i + 11]; s11 += d * d; }
        if (r > 12) { double d = a[ao + i + 12] - b[bo + i + 12]; s12 += d * d; }
        if (r > 13) { double d = a[ao + i + 13] - b[bo + i + 13]; s13 += d * d; }
        if (r > 14) { double d = a[ao + i + 14] - b[bo + i + 14]; s14 += d * d; }
        return laneTree(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15);
    }

    /** One block (a, b, c); element j goes to lane j % 16. */
    static double blkSumSqMulAdd(double[] a, int ao, double[] b, int bo, double[] c, int co, int m) {
        double s0 = 0; double s1 = 0; double s2 = 0; double s3 = 0; double s4 = 0; double s5 = 0; double s6 = 0; double s7 = 0; double s8 = 0; double s9 = 0; double s10 = 0; double s11 = 0; double s12 = 0; double s13 = 0; double s14 = 0; double s15 = 0;
        int i = 0;
        for (; i + 16 <= m; i += 16) {
            { double t = a[ao + i + 0] * b[bo + i + 0] + c[co + i + 0]; s0 += t * t; }
            { double t = a[ao + i + 1] * b[bo + i + 1] + c[co + i + 1]; s1 += t * t; }
            { double t = a[ao + i + 2] * b[bo + i + 2] + c[co + i + 2]; s2 += t * t; }
            { double t = a[ao + i + 3] * b[bo + i + 3] + c[co + i + 3]; s3 += t * t; }
            { double t = a[ao + i + 4] * b[bo + i + 4] + c[co + i + 4]; s4 += t * t; }
            { double t = a[ao + i + 5] * b[bo + i + 5] + c[co + i + 5]; s5 += t * t; }
            { double t = a[ao + i + 6] * b[bo + i + 6] + c[co + i + 6]; s6 += t * t; }
            { double t = a[ao + i + 7] * b[bo + i + 7] + c[co + i + 7]; s7 += t * t; }
            { double t = a[ao + i + 8] * b[bo + i + 8] + c[co + i + 8]; s8 += t * t; }
            { double t = a[ao + i + 9] * b[bo + i + 9] + c[co + i + 9]; s9 += t * t; }
            { double t = a[ao + i + 10] * b[bo + i + 10] + c[co + i + 10]; s10 += t * t; }
            { double t = a[ao + i + 11] * b[bo + i + 11] + c[co + i + 11]; s11 += t * t; }
            { double t = a[ao + i + 12] * b[bo + i + 12] + c[co + i + 12]; s12 += t * t; }
            { double t = a[ao + i + 13] * b[bo + i + 13] + c[co + i + 13]; s13 += t * t; }
            { double t = a[ao + i + 14] * b[bo + i + 14] + c[co + i + 14]; s14 += t * t; }
            { double t = a[ao + i + 15] * b[bo + i + 15] + c[co + i + 15]; s15 += t * t; }
        }
        int r = m - i;
        if (r > 0) { double t = a[ao + i + 0] * b[bo + i + 0] + c[co + i + 0]; s0 += t * t; }
        if (r > 1) { double t = a[ao + i + 1] * b[bo + i + 1] + c[co + i + 1]; s1 += t * t; }
        if (r > 2) { double t = a[ao + i + 2] * b[bo + i + 2] + c[co + i + 2]; s2 += t * t; }
        if (r > 3) { double t = a[ao + i + 3] * b[bo + i + 3] + c[co + i + 3]; s3 += t * t; }
        if (r > 4) { double t = a[ao + i + 4] * b[bo + i + 4] + c[co + i + 4]; s4 += t * t; }
        if (r > 5) { double t = a[ao + i + 5] * b[bo + i + 5] + c[co + i + 5]; s5 += t * t; }
        if (r > 6) { double t = a[ao + i + 6] * b[bo + i + 6] + c[co + i + 6]; s6 += t * t; }
        if (r > 7) { double t = a[ao + i + 7] * b[bo + i + 7] + c[co + i + 7]; s7 += t * t; }
        if (r > 8) { double t = a[ao + i + 8] * b[bo + i + 8] + c[co + i + 8]; s8 += t * t; }
        if (r > 9) { double t = a[ao + i + 9] * b[bo + i + 9] + c[co + i + 9]; s9 += t * t; }
        if (r > 10) { double t = a[ao + i + 10] * b[bo + i + 10] + c[co + i + 10]; s10 += t * t; }
        if (r > 11) { double t = a[ao + i + 11] * b[bo + i + 11] + c[co + i + 11]; s11 += t * t; }
        if (r > 12) { double t = a[ao + i + 12] * b[bo + i + 12] + c[co + i + 12]; s12 += t * t; }
        if (r > 13) { double t = a[ao + i + 13] * b[bo + i + 13] + c[co + i + 13]; s13 += t * t; }
        if (r > 14) { double t = a[ao + i + 14] * b[bo + i + 14] + c[co + i + 14]; s14 += t * t; }
        return laneTree(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15);
    }

    /** One block (x[xo..]); element j goes to lane j % 16. */
    static double blkSumSq(double[] x, int xo, int m) {
        double s0 = 0; double s1 = 0; double s2 = 0; double s3 = 0; double s4 = 0; double s5 = 0; double s6 = 0; double s7 = 0; double s8 = 0; double s9 = 0; double s10 = 0; double s11 = 0; double s12 = 0; double s13 = 0; double s14 = 0; double s15 = 0;
        int i = 0;
        for (; i + 16 <= m; i += 16) {
            { double v = x[xo + i + 0]; s0 += v * v; }
            { double v = x[xo + i + 1]; s1 += v * v; }
            { double v = x[xo + i + 2]; s2 += v * v; }
            { double v = x[xo + i + 3]; s3 += v * v; }
            { double v = x[xo + i + 4]; s4 += v * v; }
            { double v = x[xo + i + 5]; s5 += v * v; }
            { double v = x[xo + i + 6]; s6 += v * v; }
            { double v = x[xo + i + 7]; s7 += v * v; }
            { double v = x[xo + i + 8]; s8 += v * v; }
            { double v = x[xo + i + 9]; s9 += v * v; }
            { double v = x[xo + i + 10]; s10 += v * v; }
            { double v = x[xo + i + 11]; s11 += v * v; }
            { double v = x[xo + i + 12]; s12 += v * v; }
            { double v = x[xo + i + 13]; s13 += v * v; }
            { double v = x[xo + i + 14]; s14 += v * v; }
            { double v = x[xo + i + 15]; s15 += v * v; }
        }
        int r = m - i;
        if (r > 0) { double v = x[xo + i + 0]; s0 += v * v; }
        if (r > 1) { double v = x[xo + i + 1]; s1 += v * v; }
        if (r > 2) { double v = x[xo + i + 2]; s2 += v * v; }
        if (r > 3) { double v = x[xo + i + 3]; s3 += v * v; }
        if (r > 4) { double v = x[xo + i + 4]; s4 += v * v; }
        if (r > 5) { double v = x[xo + i + 5]; s5 += v * v; }
        if (r > 6) { double v = x[xo + i + 6]; s6 += v * v; }
        if (r > 7) { double v = x[xo + i + 7]; s7 += v * v; }
        if (r > 8) { double v = x[xo + i + 8]; s8 += v * v; }
        if (r > 9) { double v = x[xo + i + 9]; s9 += v * v; }
        if (r > 10) { double v = x[xo + i + 10]; s10 += v * v; }
        if (r > 11) { double v = x[xo + i + 11]; s11 += v * v; }
        if (r > 12) { double v = x[xo + i + 12]; s12 += v * v; }
        if (r > 13) { double v = x[xo + i + 13]; s13 += v * v; }
        if (r > 14) { double v = x[xo + i + 14]; s14 += v * v; }
        return laneTree(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15);
    }
}
