!> GENERATED by native/gen_elementwise.py -- do not edit by hand.
!>
!> numj elementwise kernels (float64): out = a op b, scalar operands, in-place updates, bitwise copies.
!> Contiguous entry points take plain pointers; n-d entry points take a descriptor of extents and element
!> strides (any sign, zero for broadcast operands) and walk rows along the innermost axis. Each row is
!> dispatched to a unit-stride kernel when its strides allow (the common case after the Java layer coalesces
!> axes) and to a general strided loop otherwise.
!>
!> Every result element is a single correctly rounded IEEE-754 operation (built with -ffp-contract=off), so
!> results are bitwise identical to Java's and NumPy's for any layout, path or thread count.
!> Aliasing contract: see gen_elementwise.py. Bounds and lifetimes are validated by the Java layer.
module numj_elementwise
  use, intrinsic :: iso_c_binding, only: c_double, c_int, c_int64_t
  implicit none
  private

  integer, parameter :: dp = c_double
  integer(c_int), parameter :: OP_ADD = 1
  integer(c_int), parameter :: OP_SUB = 2
  integer(c_int), parameter :: OP_MUL = 3
  integer(c_int), parameter :: OP_DIV = 4
  integer(c_int), parameter :: OP_RSUB = 5
  integer(c_int), parameter :: OP_RDIV = 6
  !> Elements per OpenMP work item in the contiguous kernels.
  integer(c_int64_t), parameter :: CHUNK = 32768_c_int64_t

  public :: numj_ew_contig, numj_ew_contig_s, numj_ew_contig_ip, numj_ew_contig_ip_s, numj_ew_contig_self, &
            numj_ew_nd, numj_ew_nd_ip, numj_ew_nd_self, numj_copy_nd

contains

  ! ------------------------------------------------------------------------------------------------
  ! Unit-stride kernels
  ! ------------------------------------------------------------------------------------------------

  !> out = a op b
  subroutine ew_vv(op, m, a, b, out)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m
    real(dp), intent(in) :: a(m), b(m)
    real(dp), intent(out) :: out(m)
    select case (op)
    case (OP_ADD)
      out = a + b
    case (OP_SUB)
      out = a - b
    case (OP_MUL)
      out = a * b
    case (OP_DIV)
      out = a / b
    case (OP_RSUB)
      out = b - a
    case (OP_RDIV)
      out = b / a
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_vv

  !> out = a op s
  subroutine ew_vs(op, m, a, s, out)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m
    real(dp), intent(in) :: a(m), s
    real(dp), intent(out) :: out(m)
    select case (op)
    case (OP_ADD)
      out = a + s
    case (OP_SUB)
      out = a - s
    case (OP_MUL)
      out = a * s
    case (OP_DIV)
      out = a / s
    case (OP_RSUB)
      out = s - a
    case (OP_RDIV)
      out = s / a
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_vs

  !> x = x op y
  subroutine ew_ip_vv(op, m, x, y)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m
    real(dp), intent(inout) :: x(m)
    real(dp), intent(in) :: y(m)
    select case (op)
    case (OP_ADD)
      x = x + y
    case (OP_SUB)
      x = x - y
    case (OP_MUL)
      x = x * y
    case (OP_DIV)
      x = x / y
    case (OP_RSUB)
      x = y - x
    case (OP_RDIV)
      x = y / x
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_ip_vv

  !> x = x op s
  subroutine ew_ip_vs(op, m, x, s)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m
    real(dp), intent(inout) :: x(m)
    real(dp), intent(in) :: s
    select case (op)
    case (OP_ADD)
      x = x + s
    case (OP_SUB)
      x = x - s
    case (OP_MUL)
      x = x * s
    case (OP_DIV)
      x = x / s
    case (OP_RSUB)
      x = s - x
    case (OP_RDIV)
      x = s / x
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_ip_vs

  !> x = x op x
  subroutine ew_self(op, m, x)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m
    real(dp), intent(inout) :: x(m)
    select case (op)
    case (OP_ADD)
      x = x + x
    case (OP_SUB)
      x = x - x
    case (OP_MUL)
      x = x * x
    case (OP_DIV)
      x = x / x
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_self

  ! ------------------------------------------------------------------------------------------------
  ! General strided rows
  ! ------------------------------------------------------------------------------------------------

  subroutine ew_strided(op, m, out, io, ko, a, ia, ka, b, ib, kb)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m, io, ko, ia, ka, ib, kb
    real(dp), intent(inout) :: out(0:*)
    real(dp), intent(in) :: a(0:*), b(0:*)
    integer(c_int64_t) :: j
    select case (op)
    case (OP_ADD)
      do j = 0, m - 1
        out(io + j*ko) = a(ia + j*ka) + b(ib + j*kb)
      end do
    case (OP_SUB)
      do j = 0, m - 1
        out(io + j*ko) = a(ia + j*ka) - b(ib + j*kb)
      end do
    case (OP_MUL)
      do j = 0, m - 1
        out(io + j*ko) = a(ia + j*ka) * b(ib + j*kb)
      end do
    case (OP_DIV)
      do j = 0, m - 1
        out(io + j*ko) = a(ia + j*ka) / b(ib + j*kb)
      end do
    case (OP_RSUB)
      do j = 0, m - 1
        out(io + j*ko) = b(ib + j*kb) - a(ia + j*ka)
      end do
    case (OP_RDIV)
      do j = 0, m - 1
        out(io + j*ko) = b(ib + j*kb) / a(ia + j*ka)
      end do
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_strided

  subroutine ew_ip_strided(op, m, x, ix, kx, y, iy, ky)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m, ix, kx, iy, ky
    real(dp), intent(inout) :: x(0:*)
    real(dp), intent(in) :: y(0:*)
    integer(c_int64_t) :: j
    select case (op)
    case (OP_ADD)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) + y(iy + j*ky)
      end do
    case (OP_SUB)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) - y(iy + j*ky)
      end do
    case (OP_MUL)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) * y(iy + j*ky)
      end do
    case (OP_DIV)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) / y(iy + j*ky)
      end do
    case (OP_RSUB)
      do j = 0, m - 1
        x(ix + j*kx) = y(iy + j*ky) - x(ix + j*kx)
      end do
    case (OP_RDIV)
      do j = 0, m - 1
        x(ix + j*kx) = y(iy + j*ky) / x(ix + j*kx)
      end do
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_ip_strided

  subroutine ew_self_strided(op, m, x, ix, kx)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m, ix, kx
    real(dp), intent(inout) :: x(0:*)
    integer(c_int64_t) :: j
    select case (op)
    case (OP_ADD)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) + x(ix + j*kx)
      end do
    case (OP_SUB)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) - x(ix + j*kx)
      end do
    case (OP_MUL)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) * x(ix + j*kx)
      end do
    case (OP_DIV)
      do j = 0, m - 1
        x(ix + j*kx) = x(ix + j*kx) / x(ix + j*kx)
      end do
    case default
      error stop 'numj: bad elementwise op'
    end select
  end subroutine ew_self_strided

  ! ------------------------------------------------------------------------------------------------
  ! Row dispatch: pick the unit-stride kernel when the row allows it (sequence association passes the
  ! row's first element; no copies). Swapping operands uses the reversed op (x - y == -(y - x) is NOT used;
  ! RSUB/RDIV evaluate y - x and y / x directly, so every result is the same single rounding).
  ! ------------------------------------------------------------------------------------------------

  pure function reversed(op) result(r)
    integer(c_int), intent(in) :: op
    integer(c_int) :: r
    select case (op)
    case (OP_SUB); r = OP_RSUB
    case (OP_DIV); r = OP_RDIV
    case (OP_RSUB); r = OP_SUB
    case (OP_RDIV); r = OP_DIV
    case default; r = op
    end select
  end function reversed

  subroutine row_oop(op, m, out, io, ko, a, ia, ka, b, ib, kb)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m, io, ko, ia, ka, ib, kb
    real(dp), intent(inout) :: out(0:*)
    real(dp), intent(in) :: a(0:*), b(0:*)
    if (ko == 1 .and. ka == 1 .and. kb == 1) then
      call ew_vv(op, m, a(ia), b(ib), out(io))
    else if (ko == 1 .and. ka == 1 .and. kb == 0) then
      call ew_vs(op, m, a(ia), b(ib), out(io))
    else if (ko == 1 .and. ka == 0 .and. kb == 1) then
      call ew_vs(reversed(op), m, b(ib), a(ia), out(io))
    else
      call ew_strided(op, m, out, io, ko, a, ia, ka, b, ib, kb)
    end if
  end subroutine row_oop

  subroutine row_ip(op, m, x, ix, kx, y, iy, ky)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m, ix, kx, iy, ky
    real(dp), intent(inout) :: x(0:*)
    real(dp), intent(in) :: y(0:*)
    if (kx == 1 .and. ky == 1) then
      call ew_ip_vv(op, m, x(ix), y(iy))
    else if (kx == 1 .and. ky == 0) then
      call ew_ip_vs(op, m, x(ix), y(iy))
    else
      call ew_ip_strided(op, m, x, ix, kx, y, iy, ky)
    end if
  end subroutine row_ip

  subroutine row_self(op, m, x, ix, kx)
    integer(c_int), intent(in) :: op
    integer(c_int64_t), intent(in) :: m, ix, kx
    real(dp), intent(inout) :: x(0:*)
    if (kx == 1) then
      call ew_self(op, m, x(ix))
    else
      call ew_self_strided(op, m, x, ix, kx)
    end if
  end subroutine row_self

  subroutine row_copy(m, out, io, ko, a, ia, ka)
    integer(c_int64_t), intent(in) :: m, io, ko, ia, ka
    real(dp), intent(inout) :: out(0:*)
    real(dp), intent(in) :: a(0:*)
    integer(c_int64_t) :: j
    if (ko == 1 .and. ka == 1) then
      out(io:io + m - 1) = a(ia:ia + m - 1)
    else if (ko == 1 .and. ka == 0) then
      out(io:io + m - 1) = a(ia)
    else
      do j = 0, m - 1
        out(io + j*ko) = a(ia + j*ka)
      end do
    end if
  end subroutine row_copy

  ! ------------------------------------------------------------------------------------------------
  ! Index helpers (dim 1 innermost; "rows" enumerate dims 2..nd in C order)
  ! ------------------------------------------------------------------------------------------------

  !> Odometer state (idx(2:nd)) of row r.
  pure subroutine unravel_index(r, nd, shape, idx)
    integer(c_int64_t), intent(in) :: r
    integer(c_int), intent(in) :: nd
    integer(c_int64_t), intent(in) :: shape(nd)
    integer(c_int64_t), intent(out) :: idx(nd)
    integer(c_int64_t) :: q
    integer :: k
    idx = 0
    q = r
    do k = 2, nd
      idx(k) = mod(q, shape(k))
      q = q / shape(k)
    end do
  end subroutine unravel_index

  !> Element offset of the first element of row r for one operand.
  pure function offset_of(r, nd, shape, stride) result(off)
    integer(c_int64_t), intent(in) :: r
    integer(c_int), intent(in) :: nd
    integer(c_int64_t), intent(in) :: shape(nd), stride(nd)
    integer(c_int64_t) :: off, q
    integer :: k
    off = 0
    q = r
    do k = 2, nd
      off = off + mod(q, shape(k)) * stride(k)
      q = q / shape(k)
    end do
  end function offset_of

  ! ------------------------------------------------------------------------------------------------
  ! C ABI: contiguous
  ! ------------------------------------------------------------------------------------------------

  !> out(1:n) = a op b. out is disjoint from a and b.
  subroutine numj_ew_contig(op, n, a, b, out, nthreads) bind(C, name='numj_ew_contig')
    integer(c_int), value :: op, nthreads
    integer(c_int64_t), value :: n
    real(c_double), intent(in) :: a(n), b(n)
    real(c_double), intent(out) :: out(n)
    integer(c_int64_t) :: k, lo, hi
    if (nthreads > 1 .and. n > CHUNK) then
      !$omp parallel do num_threads(nthreads) schedule(static) private(lo, hi)
      do k = 0, (n - 1) / CHUNK
        lo = k*CHUNK + 1
        hi = min(n, lo + CHUNK - 1)
        call ew_vv(op, hi - lo + 1, a(lo), b(lo), out(lo))
      end do
      !$omp end parallel do
    else
      call ew_vv(op, n, a, b, out)
    end if
  end subroutine numj_ew_contig

  !> out(1:n) = a op s. out is disjoint from a.
  subroutine numj_ew_contig_s(op, n, a, s, out, nthreads) bind(C, name='numj_ew_contig_s')
    integer(c_int), value :: op, nthreads
    integer(c_int64_t), value :: n
    real(c_double), value :: s
    real(c_double), intent(in) :: a(n)
    real(c_double), intent(out) :: out(n)
    integer(c_int64_t) :: k, lo, hi
    if (nthreads > 1 .and. n > CHUNK) then
      !$omp parallel do num_threads(nthreads) schedule(static) private(lo, hi)
      do k = 0, (n - 1) / CHUNK
        lo = k*CHUNK + 1
        hi = min(n, lo + CHUNK - 1)
        call ew_vs(op, hi - lo + 1, a(lo), s, out(lo))
      end do
      !$omp end parallel do
    else
      call ew_vs(op, n, a, s, out)
    end if
  end subroutine numj_ew_contig_s

  !> x(1:n) = x op y. y is disjoint from x.
  subroutine numj_ew_contig_ip(op, n, x, y, nthreads) bind(C, name='numj_ew_contig_ip')
    integer(c_int), value :: op, nthreads
    integer(c_int64_t), value :: n
    real(c_double), intent(inout) :: x(n)
    real(c_double), intent(in) :: y(n)
    integer(c_int64_t) :: k, lo, hi
    if (nthreads > 1 .and. n > CHUNK) then
      !$omp parallel do num_threads(nthreads) schedule(static) private(lo, hi)
      do k = 0, (n - 1) / CHUNK
        lo = k*CHUNK + 1
        hi = min(n, lo + CHUNK - 1)
        call ew_ip_vv(op, hi - lo + 1, x(lo), y(lo))
      end do
      !$omp end parallel do
    else
      call ew_ip_vv(op, n, x, y)
    end if
  end subroutine numj_ew_contig_ip

  !> x(1:n) = x op s.
  subroutine numj_ew_contig_ip_s(op, n, x, s, nthreads) bind(C, name='numj_ew_contig_ip_s')
    integer(c_int), value :: op, nthreads
    integer(c_int64_t), value :: n
    real(c_double), value :: s
    real(c_double), intent(inout) :: x(n)
    integer(c_int64_t) :: k, lo, hi
    if (nthreads > 1 .and. n > CHUNK) then
      !$omp parallel do num_threads(nthreads) schedule(static) private(lo, hi)
      do k = 0, (n - 1) / CHUNK
        lo = k*CHUNK + 1
        hi = min(n, lo + CHUNK - 1)
        call ew_ip_vs(op, hi - lo + 1, x(lo), s)
      end do
      !$omp end parallel do
    else
      call ew_ip_vs(op, n, x, s)
    end if
  end subroutine numj_ew_contig_ip_s

  !> x(1:n) = x op x.
  subroutine numj_ew_contig_self(op, n, x, nthreads) bind(C, name='numj_ew_contig_self')
    integer(c_int), value :: op, nthreads
    integer(c_int64_t), value :: n
    real(c_double), intent(inout) :: x(n)
    integer(c_int64_t) :: k, lo, hi
    if (nthreads > 1 .and. n > CHUNK) then
      !$omp parallel do num_threads(nthreads) schedule(static) private(lo, hi)
      do k = 0, (n - 1) / CHUNK
        lo = k*CHUNK + 1
        hi = min(n, lo + CHUNK - 1)
        call ew_self(op, hi - lo + 1, x(lo))
      end do
      !$omp end parallel do
    else
      call ew_self(op, n, x)
    end if
  end subroutine numj_ew_contig_self

  ! ------------------------------------------------------------------------------------------------
  ! C ABI: n-d strided
  ! ------------------------------------------------------------------------------------------------

  !> out = a op b over n-d strided operands (out disjoint from a and b).
  !> desc(nd, 4): column 1 = extents, columns 2.. = element strides of out, a, b;
  !> dim 1 is the innermost (fastest) axis. o* = element offset of the first logical element from the pointer.
  subroutine numj_ew_nd(op, nd, desc, out, oout, a, oa, b, ob, nthreads) bind(C, name='numj_ew_nd')
    integer(c_int), value :: nd, nthreads
    integer(c_int64_t), intent(in) :: desc(nd, 4)
    integer(c_int64_t), value :: oout, oa, ob
    integer(c_int), value :: op
    real(c_double), intent(inout) :: out(0:*)
    real(c_double), intent(in) :: a(0:*), b(0:*)
    integer(c_int64_t) :: nrows, r0, r1, chunk, t
    nrows = 1
    if (nd > 1) nrows = product(desc(2:nd, 1))
    if (nthreads > 1 .and. nrows > 1) then
      chunk = (nrows + nthreads - 1) / nthreads
      !$omp parallel do num_threads(nthreads) schedule(static, 1) private(r0, r1)
      do t = 0, nthreads - 1
        r0 = t * chunk
        r1 = min(nrows, r0 + chunk) - 1
        if (r0 <= r1) call rows(r0, r1)
      end do
      !$omp end parallel do
    else
      call rows(0_c_int64_t, nrows - 1)
    end if

  contains

    subroutine rows(r0, r1)
      integer(c_int64_t), intent(in) :: r0, r1
      integer(c_int64_t) :: r, pout, pa, pb, idx(nd)
      integer :: kk
      pout = oout + offset_of(r0, nd, desc(:, 1), desc(:, 2))
      pa = oa + offset_of(r0, nd, desc(:, 1), desc(:, 3))
      pb = ob + offset_of(r0, nd, desc(:, 1), desc(:, 4))
      call unravel_index(r0, nd, desc(:, 1), idx)
      do r = r0, r1
        call row_oop(op, desc(1, 1), out, pout, desc(1, 2), a, pa, desc(1, 3), b, pb, desc(1, 4))
        kk = 2
        do while (kk <= nd)
          idx(kk) = idx(kk) + 1
          pout = pout + desc(kk, 2)
          pa = pa + desc(kk, 3)
          pb = pb + desc(kk, 4)
          if (idx(kk) < desc(kk, 1)) exit
          pout = pout - desc(kk, 2) * desc(kk, 1)
          pa = pa - desc(kk, 3) * desc(kk, 1)
          pb = pb - desc(kk, 4) * desc(kk, 1)
          idx(kk) = 0
          kk = kk + 1
        end do
      end do
    end subroutine rows

  end subroutine numj_ew_nd

  !> x = x op y over n-d strided operands (y disjoint from x).
  !> desc(nd, 3): column 1 = extents, columns 2.. = element strides of x, y;
  !> dim 1 is the innermost (fastest) axis. o* = element offset of the first logical element from the pointer.
  subroutine numj_ew_nd_ip(op, nd, desc, x, ox, y, oy, nthreads) bind(C, name='numj_ew_nd_ip')
    integer(c_int), value :: nd, nthreads
    integer(c_int64_t), intent(in) :: desc(nd, 3)
    integer(c_int64_t), value :: ox, oy
    integer(c_int), value :: op
    real(c_double), intent(inout) :: x(0:*)
    real(c_double), intent(in) :: y(0:*)
    integer(c_int64_t) :: nrows, r0, r1, chunk, t
    nrows = 1
    if (nd > 1) nrows = product(desc(2:nd, 1))
    if (nthreads > 1 .and. nrows > 1) then
      chunk = (nrows + nthreads - 1) / nthreads
      !$omp parallel do num_threads(nthreads) schedule(static, 1) private(r0, r1)
      do t = 0, nthreads - 1
        r0 = t * chunk
        r1 = min(nrows, r0 + chunk) - 1
        if (r0 <= r1) call rows(r0, r1)
      end do
      !$omp end parallel do
    else
      call rows(0_c_int64_t, nrows - 1)
    end if

  contains

    subroutine rows(r0, r1)
      integer(c_int64_t), intent(in) :: r0, r1
      integer(c_int64_t) :: r, px, py, idx(nd)
      integer :: kk
      px = ox + offset_of(r0, nd, desc(:, 1), desc(:, 2))
      py = oy + offset_of(r0, nd, desc(:, 1), desc(:, 3))
      call unravel_index(r0, nd, desc(:, 1), idx)
      do r = r0, r1
        call row_ip(op, desc(1, 1), x, px, desc(1, 2), y, py, desc(1, 3))
        kk = 2
        do while (kk <= nd)
          idx(kk) = idx(kk) + 1
          px = px + desc(kk, 2)
          py = py + desc(kk, 3)
          if (idx(kk) < desc(kk, 1)) exit
          px = px - desc(kk, 2) * desc(kk, 1)
          py = py - desc(kk, 3) * desc(kk, 1)
          idx(kk) = 0
          kk = kk + 1
        end do
      end do
    end subroutine rows

  end subroutine numj_ew_nd_ip

  !> x = x op x over an n-d strided operand.
  !> desc(nd, 2): column 1 = extents, columns 2.. = element strides of x;
  !> dim 1 is the innermost (fastest) axis. o* = element offset of the first logical element from the pointer.
  subroutine numj_ew_nd_self(op, nd, desc, x, ox, nthreads) bind(C, name='numj_ew_nd_self')
    integer(c_int), value :: nd, nthreads
    integer(c_int64_t), intent(in) :: desc(nd, 2)
    integer(c_int64_t), value :: ox
    integer(c_int), value :: op
    real(c_double), intent(inout) :: x(0:*)
    integer(c_int64_t) :: nrows, r0, r1, chunk, t
    nrows = 1
    if (nd > 1) nrows = product(desc(2:nd, 1))
    if (nthreads > 1 .and. nrows > 1) then
      chunk = (nrows + nthreads - 1) / nthreads
      !$omp parallel do num_threads(nthreads) schedule(static, 1) private(r0, r1)
      do t = 0, nthreads - 1
        r0 = t * chunk
        r1 = min(nrows, r0 + chunk) - 1
        if (r0 <= r1) call rows(r0, r1)
      end do
      !$omp end parallel do
    else
      call rows(0_c_int64_t, nrows - 1)
    end if

  contains

    subroutine rows(r0, r1)
      integer(c_int64_t), intent(in) :: r0, r1
      integer(c_int64_t) :: r, px, idx(nd)
      integer :: kk
      px = ox + offset_of(r0, nd, desc(:, 1), desc(:, 2))
      call unravel_index(r0, nd, desc(:, 1), idx)
      do r = r0, r1
        call row_self(op, desc(1, 1), x, px, desc(1, 2))
        kk = 2
        do while (kk <= nd)
          idx(kk) = idx(kk) + 1
          px = px + desc(kk, 2)
          if (idx(kk) < desc(kk, 1)) exit
          px = px - desc(kk, 2) * desc(kk, 1)
          idx(kk) = 0
          kk = kk + 1
        end do
      end do
    end subroutine rows

  end subroutine numj_ew_nd_self

  !> out = a (bitwise copy) over n-d strided operands (out disjoint from a).
  !> desc(nd, 3): column 1 = extents, columns 2.. = element strides of out, a;
  !> dim 1 is the innermost (fastest) axis. o* = element offset of the first logical element from the pointer.
  subroutine numj_copy_nd(nd, desc, out, oout, a, oa, nthreads) bind(C, name='numj_copy_nd')
    integer(c_int), value :: nd, nthreads
    integer(c_int64_t), intent(in) :: desc(nd, 3)
    integer(c_int64_t), value :: oout, oa
    real(c_double), intent(inout) :: out(0:*)
    real(c_double), intent(in) :: a(0:*)
    integer(c_int64_t) :: nrows, r0, r1, chunk, t
    nrows = 1
    if (nd > 1) nrows = product(desc(2:nd, 1))
    if (nthreads > 1 .and. nrows > 1) then
      chunk = (nrows + nthreads - 1) / nthreads
      !$omp parallel do num_threads(nthreads) schedule(static, 1) private(r0, r1)
      do t = 0, nthreads - 1
        r0 = t * chunk
        r1 = min(nrows, r0 + chunk) - 1
        if (r0 <= r1) call rows(r0, r1)
      end do
      !$omp end parallel do
    else
      call rows(0_c_int64_t, nrows - 1)
    end if

  contains

    subroutine rows(r0, r1)
      integer(c_int64_t), intent(in) :: r0, r1
      integer(c_int64_t) :: r, pout, pa, idx(nd)
      integer :: kk
      pout = oout + offset_of(r0, nd, desc(:, 1), desc(:, 2))
      pa = oa + offset_of(r0, nd, desc(:, 1), desc(:, 3))
      call unravel_index(r0, nd, desc(:, 1), idx)
      do r = r0, r1
        call row_copy(desc(1, 1), out, pout, desc(1, 2), a, pa, desc(1, 3))
        kk = 2
        do while (kk <= nd)
          idx(kk) = idx(kk) + 1
          pout = pout + desc(kk, 2)
          pa = pa + desc(kk, 3)
          if (idx(kk) < desc(kk, 1)) exit
          pout = pout - desc(kk, 2) * desc(kk, 1)
          pa = pa - desc(kk, 3) * desc(kk, 1)
          idx(kk) = 0
          kk = kk + 1
        end do
      end do
    end subroutine rows

  end subroutine numj_copy_nd

end module numj_elementwise
