"""Builds results/nd/RESULTS.md from the JMH JSON and Python CSV written by scripts/bench_nd.ps1.

Statistics: every implementation is summarised by the median, p10 and p90 of its per-call times (JMH: all
measurement iterations of all forks; Python: all samples). Verdict for numj against another implementation:
  win  if numj's p90 < the other's p10;   loss if numj's p10 > the other's p90;   tie otherwise.
Ratios are other/numj medians (> 1 means numj is faster).

Usage: python -I bench/report_nd.py results/nd
"""
import csv
import json
import os
import statistics
import sys

D = sys.argv[1] if len(sys.argv) > 1 else os.path.join("results", "nd")


def pct(s, p):
    s = sorted(s)
    idx = p * (len(s) - 1)
    lo, hi = int(idx), min(int(idx) + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (idx - lo)


def load_jmh(name):
    path = os.path.join(D, name)
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return {}
    out = {}
    unit_scale = {"ns/op": 1.0, "us/op": 1e3, "ms/op": 1e6}
    for e in json.load(open(path, encoding="utf-8")):
        cls, meth = e["benchmark"].rsplit(".", 1)
        cls = cls.split("numj.", 1)[1].replace("$", ".")
        scale = unit_scale[e["primaryMetric"]["scoreUnit"]]
        raw = [v * scale for fork in e["primaryMetric"]["rawData"] for v in fork]
        key = (cls, meth, tuple(sorted(e.get("params", {}).items())))
        out[key] = {"median": statistics.median(raw), "p10": pct(raw, 0.1), "p90": pct(raw, 0.9),
                    "mean": e["primaryMetric"]["score"] * scale, "err": e["primaryMetric"]["scoreError"] * scale,
                    "n": len(raw), "forks": len(e["primaryMetric"]["rawData"])}
    return out


def load_py(name):
    path = os.path.join(D, name)
    if not os.path.exists(path):
        return {}
    out = {}
    for r in csv.DictReader(open(path, encoding="utf-8")):
        key = (r["suite"], r["kernel"], r["layout"], int(r["n"]), r["impl"])
        out[key] = {"median": float(r["median_ns"]), "p10": float(r["p10_ns"]), "p90": float(r["p90_ns"]),
                    "cv": float(r["stdev_ns"]) / float(r["mean_ns"])}
    return out


def fmt(ns):
    if ns is None:
        return "-"
    if ns < 1e3:
        return f"{ns:.1f} ns"
    if ns < 1e6:
        return f"{ns / 1e3:.2f} µs"
    return f"{ns / 1e6:.2f} ms"


def verdict(numj, other):
    if numj is None or other is None:
        return None
    if numj["p90"] < other["p10"]:
        return "win"
    if numj["p10"] > other["p90"]:
        return "loss"
    return "tie"


def ratio(numj, other):
    if numj is None or other is None:
        return "-"
    v = verdict(numj, other)
    r = other["median"] / numj["median"]
    mark = {"win": "", "loss": " **loss**", "tie": " tie"}[v]
    return f"{r:.2g}{mark}" if r < 10 else f"{r:.0f}{mark}"


tally = {}


def count(name, numj, other):
    v = verdict(numj, other)
    if v:
        tally.setdefault(name, {"win": 0, "tie": 0, "loss": 0})[v] += 1


def j(jmh, cls, meth, **params):
    return jmh.get((cls, meth, tuple(sorted((k, str(v)) for k, v in params.items()))))


def main():
    jm_before_short = load_jmh("jmh_main.json")
    jm = dict(jm_before_short)
    jm.update(load_jmh("jmh_shortfix.json"))         # ShortRowBench re-measured after the short-row fix
    jm_round1 = dict(jm)
    jm.update(load_jmh("jmh_fix2.json"))             # Reduce/Fused/ShortRow re-measured after round 2 (gather)
    jm_gather = dict(jm)
    jm.update(load_jmh("jmh_fix3.json"))             # Reduce/Fused after the tiled gather (all sizes)
    jm_tiled = dict(jm)
    jm.update(load_jmh("jmh_fix4.json"))             # final: size/op-based path choice
    jm_repeat = load_jmh("jmh_fix4repeat.json")     # independent repeat of the 10^7 cases
    jd_before = load_jmh("jmh_decision.json")      # before the contiguous fast path (kept as evidence)
    jd = dict(jd_before)
    jd.update(load_jmh("jmh_decision2.json"))      # SmallBench / AllocBench re-measured after it
    py = load_py("python_main.csv")
    env = {}
    for f in ("environment_main.json", "environment_decision.json"):
        p = os.path.join(D, f)
        if os.path.exists(p):
            env = json.load(open(p, encoding="utf-8-sig"))
            break
    pyenv = {}
    if os.path.exists(os.path.join(D, "python_main_env.json")):
        pyenv = json.load(open(os.path.join(D, "python_main_env.json"), encoding="utf-8"))

    L = []
    w = L.append
    w("# numj milestone 1 — measured results (n-d arrays)\n")
    w("Generated by `bench/report_nd.py` from `jmh_*.json` and `python_main.csv` in this directory. "
      "Times are per call. Median with [p10, p90] over all measurement iterations of all JMH forks (Java) or all samples "
      "(Python). Ratio = other / numj median (> 1: numj faster). **Verdict:** win only if numj's p90 < the other's p10, "
      "loss only if numj's p10 > the other's p90, otherwise tie. All implementations are single-threaded unless stated.\n")
    if env:
        w("## Environment\n")
        w("| item | value |\n|---|---|")
        for k in ("date", "cpu", "cores", "logical", "max_mhz", "l2_kb", "l3_kb", "ram_gb", "os", "power_plan", "on_ac_power",
                  "affinity_mask", "java", "jmh", "gfortran", "native_build"):
            if k in env:
                w(f"| {k} | {str(env[k]).replace('|', '/')} |")
        for f in env.get("fortran_flags", []) if isinstance(env.get("fortran_flags"), list) else [env.get("fortran_flags")]:
            w(f"| fortran profile | `{f}` |")
        if pyenv:
            w(f"| python | {pyenv['python'].split()[0]} |")
            w(f"| numpy | {pyenv['numpy']} (BLAS: {pyenv['numpy_config']['Build Dependencies']['blas']['name']} "
              f"{pyenv['numpy_config']['Build Dependencies']['blas'].get('version', '')}) |")
            simd = pyenv["numpy_config"].get("SIMD Extensions", {})
            w(f"| numpy SIMD | baseline {simd.get('baseline')}, found {simd.get('found')} |")
            w(f"| numexpr | {pyenv.get('numexpr')} (threads {pyenv.get('numexpr_threads')}, VML {pyenv.get('numexpr_vml')}) |")
            w(f"| numba | {pyenv.get('numba')} (llvmlite {pyenv.get('llvmlite')}) |")
        w("")

    # ---------------------------------------------------------------- elementwise
    if jm or py:
        w("## Elementwise `a + b` (output reused unless noted)\n")
        w("Layouts: `contig` [n]+[n]; `transposed` A.T+B.T into C-ordered [r,c]; `stepped` a[::2]+b[::2]; "
          "`bcast` [r,c]+[c]. `numj alloc` / `numpy` allocate the result per call. Shapes for n = 16, 10³, 10⁵, 10⁷: "
          "4×4, 25×40, 250×400, 2500×4000.\n")
        w("| layout | n | numj | numj alloc | java | numpy-out | numpy | numexpr | numba | java/numj | numpy-out/numj | numexpr/numj | numba/numj |")
        w("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for layout in ("contig", "transposed", "stepped", "bcast"):
            for n in (16, 1000, 100000, 10000000):
                nj = j(jm, "ElementwiseBench", "numj", n=n, layout=layout)
                na = j(jm, "ElementwiseBench", "numjAlloc", n=n, layout=layout)
                jv = j(jm, "ElementwiseBench", "java", n=n, layout=layout)
                po = py.get(("ew", "add", layout, n, "numpy-out"))
                pa = py.get(("ew", "add", layout, n, "numpy"))
                ne = py.get(("ew", "add", layout, n, "numexpr"))
                nb = py.get(("ew", "add", layout, n, "numba"))
                for name, o in (("java", jv), ("numpy-out", po), ("numexpr", ne), ("numba", nb)):
                    count("elementwise vs " + name, nj, o)
                count("elementwise alloc vs numpy", na, pa)
                w(f"| {layout} | {n:,} | {fmt(nj and nj['median'])} | {fmt(na and na['median'])} | {fmt(jv and jv['median'])} | "
                  f"{fmt(po and po['median'])} | {fmt(pa and pa['median'])} | {fmt(ne and ne['median'])} | {fmt(nb and nb['median'])} | "
                  f"{ratio(nj, jv)} | {ratio(nj, po)} | {ratio(nj, ne)} | {ratio(nj, nb)} |")
        w("")

    # ---------------------------------------------------------------- reductions
    if jm or py:
        w("## Sums of a C-ordered [r, c] array (outputs reused)\n")
        w("`all` every element; `axis0` column sums; `axis1` row sums; `allT` every element of the transposed view "
          "(numj sums in the view's logical order, which makes its result layout-independent but walks memory with a stride); "
          "`allTmem` is the same sum with the opt-in `SumOrder.MEMORY` (memory order; compared with NumPy's `allT`). "
          "`java` and `numba` are sequential loops in memory order (one rounding chain; less accurate than numj or NumPy).\n")
        w("| kind | n | numj | java | numpy-out | numpy | numba | java/numj | numpy-out/numj | numpy/numj | numba/numj |")
        w("|---|---|---|---|---|---|---|---|---|---|---|")
        for kind in ("all", "axis0", "axis1", "allT", "allTmem"):
            for n in (1000, 100000, 10000000):
                nj = j(jm, "ReduceBench", "numj", n=n, kind=kind)
                pk = "allT" if kind == "allTmem" else kind
                jv = j(jm, "ReduceBench", "java", n=n, kind=kind)
                po = py.get(("reduce", "sum", pk, n, "numpy-out"))
                pa = py.get(("reduce", "sum", pk, n, "numpy"))
                nb = py.get(("reduce", "sum", pk, n, "numba"))
                for name, o in (("java", jv), ("numpy", po or pa), ("numba", nb)):
                    count("sum vs " + name, nj, o)
                w(f"| {kind} | {n:,} | {fmt(nj and nj['median'])} | {fmt(jv and jv['median'])} | {fmt(po and po['median'])} | "
                  f"{fmt(pa and pa['median'])} | {fmt(nb and nb['median'])} | {ratio(nj, jv)} | {ratio(nj, po)} | {ratio(nj, pa)} | {ratio(nj, nb)} |")
        w("")

    # ---------------------------------------------------------------- fused
    if jm or py:
        w("## `sum((a*b + c)**2)`: explicit fusion versus operation-by-operation\n")
        w("`numj fused` = `Expr.sum(...).evaluate()` → `sumSqMulAdd` (one pass); `numj unfused` allocates temporaries per "
          "operation; `numj reuse` reuses one temporary. `transposed` evaluates the same values through transposed views.\n")
        w("| layout | n | numj fused | numj unfused | numj reuse | java | numpy | numpy-out | numexpr | numba | numpy/fused | numpy-out/fused | numexpr/fused | numba/fused | java/fused |")
        w("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for layout in ("contig", "transposed"):
            for n in (1000, 100000, 10000000):
                f = j(jm, "FusedBench", "fused", n=n, layout=layout)
                u = j(jm, "FusedBench", "unfusedAlloc", n=n, layout=layout)
                rr = j(jm, "FusedBench", "unfusedReuse", n=n, layout=layout)
                jv = j(jm, "FusedBench", "java", n=n, layout=layout)
                pa = py.get(("fused", "muladd", layout, n, "numpy"))
                po = py.get(("fused", "muladd", layout, n, "numpy-out"))
                ne = py.get(("fused", "muladd", layout, n, "numexpr"))
                nb = py.get(("fused", "muladd", layout, n, "numba"))
                for name, o in (("numpy", pa), ("numpy-out", po), ("numexpr", ne), ("numba", nb), ("java", jv)):
                    count("fused vs " + name, f, o)
                w(f"| {layout} | {n:,} | {fmt(f and f['median'])} | {fmt(u and u['median'])} | {fmt(rr and rr['median'])} | "
                  f"{fmt(jv and jv['median'])} | {fmt(pa and pa['median'])} | {fmt(po and po['median'])} | {fmt(ne and ne['median'])} | "
                  f"{fmt(nb and nb['median'])} | {ratio(f, pa)} | {ratio(f, po)} | {ratio(f, ne)} | {ratio(f, nb)} | {ratio(f, jv)} |")
        w("")
        if pyenv.get("numba_compile_seconds"):
            w("Numba compilation (excluded from the timings above): first call per kernel, seconds — "
              + ", ".join(f"`{k}` {v[0]:.2f}" for k, v in pyenv["numba_compile_seconds"].items()) + ".\n")

    # ---------------------------------------------------------------- short rows
    if any(k[0] == "ShortRowBench" for k in jm) or any(k[0] == "short" for k in py):
        w("## Short rows (10⁶ elements in rows of k)\n")
        w("`sumRows`: row sums of a C-ordered [10⁶/k, k] array into a reused output. `addRows`: `x + y` where x, y are the "
          "first k columns of [R, k+1] arrays (rows cannot be merged, so every implementation walks R short rows).\n")
        w("| k | sumRows numj | java | numpy-out | numba | java/numj | numpy-out/numj | numba/numj | addRows numj | java | numpy-out | numexpr | numba | java/numj | numpy-out/numj | numexpr/numj | numba/numj |")
        w("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for k in (2, 4, 8, 16, 64):
            sn = j(jm, "ShortRowBench", "sumRows", k=k)
            sj = j(jm, "ShortRowBench", "javaSumRows", k=k)
            sp = py.get(("short", "sumRows", f"k={k}", 1000000, "numpy-out"))
            sb = py.get(("short", "sumRows", f"k={k}", 1000000, "numba"))
            an = j(jm, "ShortRowBench", "addRows", k=k)
            aj = j(jm, "ShortRowBench", "javaAddRows", k=k)
            ap = py.get(("short", "addRows", f"k={k}", 1000000, "numpy-out"))
            ae = py.get(("short", "addRows", f"k={k}", 1000000, "numexpr"))
            ab = py.get(("short", "addRows", f"k={k}", 1000000, "numba"))
            for name, o in (("java", sj), ("numpy-out", sp), ("numba", sb)):
                count("short-row sum vs " + name, sn, o)
            for name, o in (("java", aj), ("numpy-out", ap), ("numexpr", ae), ("numba", ab)):
                count("short-row add vs " + name, an, o)
            w(f"| {k} | {fmt(sn and sn['median'])} | {fmt(sj and sj['median'])} | {fmt(sp and sp['median'])} | {fmt(sb and sb['median'])} | "
              f"{ratio(sn, sj)} | {ratio(sn, sp)} | {ratio(sn, sb)} | {fmt(an and an['median'])} | {fmt(aj and aj['median'])} | "
              f"{fmt(ap and ap['median'])} | {fmt(ae and ae['median'])} | {fmt(ab and ab['median'])} | {ratio(an, aj)} | {ratio(an, ap)} | "
              f"{ratio(an, ae)} | {ratio(an, ab)} |")
        w("")

    if load_jmh("jmh_shortfix.json"):
        w("### Candidate retained: short-row sums (same benchmark before and after)\n")
        w("Before: every output computed its offsets with a 64-bit div/mod unravel and went through the general block "
          "machinery. After: one kept axis uses incremental offsets, and rows of at most 16 elements fill the lanes "
          "directly (same bits; tests unchanged).\n")
        w("| k | sumRows before | after | java | after/before |")
        w("|---|---|---|---|---|")
        for k in (2, 4, 8, 16, 64):
            b0 = j(jm_before_short, "ShortRowBench", "sumRows", k=k)
            a0 = j(jm, "ShortRowBench", "sumRows", k=k)
            jv = j(jm, "ShortRowBench", "javaSumRows", k=k)
            r = f"{a0['median'] / b0['median']:.2f}" if a0 and b0 else "-"
            w(f"| {k} | {fmt(b0 and b0['median'])} | {fmt(a0 and a0['median'])} | {fmt(jv and jv['median'])} | {r} |")
        w("")

    if load_jmh("jmh_fix2.json"):
        w("## Round 2: fixes for measured losses (same benchmarks before and after)\n")
        w("Three changes, all bitwise-identical (every test unchanged): column sums use groups of up to 4096 columns "
          "(512 KiB of accumulators, L2-resident) so each row is streamed once; strided sequences (transposed views, "
          "fused kernels on strided inputs) gather each 4096-element block into a buffer and run the vectorised block "
          "kernel; rows of at most 8 elements use the lane tree's closed form. The first gather version read one "
          "block at a time down a memory column (a page per element) and regressed large transposed inputs; the "
          "retained version reads 8 neighbouring logical rows per memory row (tiled). Columns: before round 2, the "
          "intermediate untiled gather, the tiled gather used at every size, and the final code, which picks the measured best "
          "path by size and operation (tiled for >= 2^20 elements, untiled gather for smaller plain sums, the direct lane "
          "loop for smaller fused kernels). `repeat` is an independent second run of the final code at 10^7 elements; "
          "the spread between `final` and `repeat` shows the run-to-run variability. NumPy figures are from the same "
          "`python_main.csv` as above.\n")
        w("| case | n / k | before | untiled gather | tiled everywhere | final | repeat | final/before | NumPy (out= where available) | NumPy/final |")
        w("|---|---|---|---|---|---|---|---|---|---|")
        rows = []
        for kind in ("axis0", "allT", "all", "axis1"):
            for n in (1000, 100000, 10000000):
                rows.append((f"sum {kind}", f"{n:,}", ("ReduceBench", "numj", {"n": n, "kind": kind}),
                             py.get(("reduce", "sum", kind, n, "numpy-out")) or py.get(("reduce", "sum", kind, n, "numpy"))))
        for layout in ("transposed", "contig"):
            for n in (1000, 100000, 10000000):
                rows.append((f"fused {layout}", f"{n:,}", ("FusedBench", "fused", {"n": n, "layout": layout}),
                             py.get(("fused", "muladd", layout, n, "numpy-out"))))
        for k in (2, 4, 8, 16, 64):
            rows.append(("short-row sum", f"k={k}", ("ShortRowBench", "sumRows", {"k": k}),
                         py.get(("short", "sumRows", f"k={k}", 1000000, "numpy-out"))))
        for name, size, (cls, m, prm), npv in rows:
            b0 = j(jm_round1, cls, m, **prm)
            g0 = j(jm_gather, cls, m, **prm)
            t0 = j(jm_tiled, cls, m, **prm)
            a0 = j(jm, cls, m, **prm)
            r0 = j(jm_repeat, cls, m, **prm)
            r = f"{a0['median'] / b0['median']:.2f}" if a0 and b0 else "-"
            w(f"| {name} | {size} | {fmt(b0 and b0['median'])} | {fmt(g0 and g0['median'])} | {fmt(t0 and t0['median'])} | "
              f"{fmt(a0 and a0['median'])} | {fmt(r0 and r0['median'])} | {r} | "
              f"{fmt(npv and npv['median'])} | {ratio(a0, npv)} |")
        w("")

    r3 = [load_jmh(f) for f in ("jmh_round3.json", "jmh_round3repeat.json", "jmh_round3third.json")]
    py3 = load_py("python_round3.csv")
    if r3[0] and py3:
        w("## Round 3: sums of transposed views\n")
        w("`allT` = default `SumOrder.LOGICAL` (layout-independent bits) after widening the tiles (up to 64 logical "
          "rows, 512 KiB budget) and removing a copy; `allTmem` = opt-in `SumOrder.MEMORY` (memory order, deterministic "
          "per layout, same error bound, not layout-independent). Three independent JMH runs (the third at 10^7 only) "
          "and a NumPy run taken right after them (`python_round3.csv`). Round-2 `allT` for reference.\n")
        w("| kind | n | round 2 | run 1 | run 2 | run 3 | NumPy (same session) | NumPy/numj (run 2) |")
        w("|---|---|---|---|---|---|---|---|")
        for kind in ("allT", "allTmem"):
            for n in (1000, 100000, 10000000):
                old = j(jm, "ReduceBench", "numj", n=n, kind="allT") if kind == "allT" else None
                rs = [j(r, "ReduceBench", "numj", n=n, kind=kind) for r in r3]
                npv = py3.get(("reduce", "sum", "allT", n, "numpy"))
                w(f"| {kind} | {n:,} | {fmt(old and old['median'])} | " + " | ".join(fmt(x and x['median']) for x in rs)
                  + f" | {fmt(npv and npv['median'])} | {ratio(rs[1], npv)} |")
        w("")

    # ---------------------------------------------------------------- decision benchmarks
    if jd:
        w("## Path selection: Java loop versus native downcall (tiny inputs)\n")
        w("Same bits on both paths; only the cost differs. Native = regular downcall.\n")
        w("| n | add java | add native | add strided java | add strided native | sum java | sum native | sqdist java | sqdist native |")
        w("|---|---|---|---|---|---|---|---|---|")
        for n in (1, 4, 16, 32, 64, 128, 256, 1024):
            cells = []
            for m in ("add", "addStrided", "sum", "sqdist"):
                for p in ("java", "native"):
                    r = j(jd, "SmallBench", m, n=n, path=p)
                    cells.append(fmt(r and r["median"]))
            w(f"| {n} | " + " | ".join(cells) + " |")
        w("")
        if jd is not jd_before and any(k[0] == "SmallBench" for k in load_jmh("jmh_decision2.json")):
            w("### Candidate retained: contiguous fast path (same benchmark before and after)\n")
            w("Before: every call built an iteration plan and descriptor and allocated segment slices. After: same-shape "
              "C-contiguous operands skip planning and use cached segments. Medians, Java path forced off (`native`) "
              "and on (`java`).\n")
            w("| n | add native before | after | add java before | after | sum native before | after | sqdist native before | after |")
            w("|---|---|---|---|---|---|---|---|---|")
            for n in (1, 16, 64, 256, 1024):
                cells = []
                for m, pth in (("add", "native"), ("add", "java"), ("sum", "native"), ("sqdist", "native")):
                    b0 = j(jd_before, "SmallBench", m, n=n, path=pth)
                    a0 = j(jd, "SmallBench", m, n=n, path=pth)
                    cells += [fmt(b0 and b0["median"]), fmt(a0 and a0["median"])]
                w(f"| {n} | " + " | ".join(cells) + " |")
            w("")
        w("## Regular versus critical downcalls (`sqdist`, Java path disabled)\n")
        w("| n | regular | critical | regular − critical |")
        w("|---|---|---|---|")
        for n in (0, 16, 1000, 65536):
            r = j(jd, "DowncallBench", "regular", n=n)
            c = j(jd, "DowncallBench.Critical", "critical", n=n)
            diff = fmt(r["median"] - c["median"]) if r and c else "-"
            w(f"| {n:,} | {fmt(r and r['median'])} | {fmt(c and c['median'])} | {diff} |")
        w("")
        w("## Native thread scaling (thresholds disabled for this measurement)\n")
        w("| op | n | 1 thread | 2 | 4 | 8 | speedup 2 | speedup 4 | speedup 8 |")
        w("|---|---|---|---|---|---|---|---|---|")
        for m in ("add", "sum", "sumAxis0"):
            for n in (100000, 1000000, 4000000, 16000000):
                rs = [j(jd, "ThreadsBench", m, n=n, threads=t) for t in (1, 2, 4, 8)]
                sp = [f"{rs[0]['median'] / r['median']:.2f}" if rs[0] and r else "-" for r in rs[1:]]
                w(f"| {m} | {n:,} | " + " | ".join(fmt(r and r["median"]) for r in rs) + " | " + " | ".join(sp) + " |")
        w("")
        w("## Allocation costs\n")
        w("`allocClose`: zero-filled owner allocated and freed; `addAlloc`: `NumJ.add(a, b)` with a fresh result; "
          "`addReuse`: into a reused buffer; `addAlloc malloc`: fresh result from non-zeroing `malloc` (candidate).\n")
        w("| n | allocClose | addReuse | addAlloc | addAlloc malloc | addAlloc − addReuse |")
        w("|---|---|---|---|---|---|")
        for n in (16, 1000, 100000, 10000000):
            ac = j(jd, "AllocBench", "allocClose", n=n)
            ar = j(jd, "AllocBench", "addReuse", n=n)
            aa = j(jd, "AllocBench", "addAlloc", n=n)
            am = j(jd, "AllocBench.Malloc", "addAllocMalloc", n=n)
            d = fmt(aa["median"] - ar["median"]) if aa and ar else "-"
            w(f"| {n:,} | {fmt(ac and ac['median'])} | {fmt(ar and ar['median'])} | {fmt(aa and aa['median'])} | {fmt(am and am['median'])} | {d} |")
        w("")

    if tally:
        w("## Wins, ties and losses (numj versus each implementation, over the cells above)\n")
        w("| comparison | win | tie | loss |")
        w("|---|---|---|---|")
        for k, v in tally.items():
            w(f"| {k} | {v['win']} | {v['tie']} | {v['loss']} |")
        w("")

    with open(os.path.join(D, "RESULTS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", os.path.join(D, "RESULTS.md"))


if __name__ == "__main__":
    main()
