"""Builds results/RESULTS.md from the benchmark CSVs. Usage: python -I bench/report.py results

Verdict rule (variability-aware): numj WINS against X only if numj's p90 < X's p10; LOSES if numj's p10 > X's p90;
otherwise the p10-p90 ranges overlap and it is a TIE. Ratios are medians: X / numj (> 1 means numj is faster).
"""
import csv
import glob
import json
import math
import os
import re
import sys

U = 2.0 ** -53


def load(path):
    if not os.path.exists(path):
        return []
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        for k in ("median_ns", "min_ns", "p10_ns", "p90_ns", "mean_ns", "stdev_ns", "result"):
            r[k] = float(r[k])
        r["n"] = int(r["n"])
        r["threads"] = int(r["threads"])
    return rows


def t(ns):
    if ns < 1e3:
        return f"{ns:.1f} ns"
    if ns < 1e6:
        return f"{ns / 1e3:.2f} µs"
    return f"{ns / 1e6:.2f} ms"


def cell(r):
    return f"{t(r['median_ns'])} <sub>({t(r['p10_ns'])}–{t(r['p90_ns'])})</sub>" if r else "—"


def verdict(numj, other):
    if not numj or not other:
        return ""
    ratio = other["median_ns"] / numj["median_ns"]
    if numj["p90_ns"] < other["p10_ns"]:
        v = "**win**"
    elif numj["p10_ns"] > other["p90_ns"]:
        v = "**lose**"
    else:
        v = "tie"
    return f"{ratio:.2f}× {v}"


def main(res):
    jm = load(os.path.join(res, "java_main.csv"))
    nm = load(os.path.join(res, "numpy_main.csv"))
    rows = jm + nm
    idx = {(r["kernel"], r["shape"], r["impl"], r["mode"]): r for r in rows}
    env = json.load(open(os.path.join(res, "environment.json"), encoding="utf-8-sig")) if os.path.exists(os.path.join(res, "environment.json")) else {}
    nenv = json.load(open(os.path.join(res, "numpy_main_env.json"))) if os.path.exists(os.path.join(res, "numpy_main_env.json")) else {}
    out = []
    w = out.append

    w("# numj benchmark results\n")
    w("_Generated by `bench/report.py` from the CSVs in this directory. Do not edit by hand._\n")

    # ---------------------------------------------------------------- environment
    w("## Environment\n")
    for k in ("date", "cpu", "cores", "logical", "l2_kb", "l3_kb", "ram_gb", "os", "power_plan", "on_ac_power", "affinity_mask", "java", "java_flags", "gfortran"):
        if k in env:
            w(f"- **{k}**: {env[k]}")
    build = ""
    log = os.path.join(res, "java_main.log")
    if os.path.exists(log):
        for line in open(log, encoding="utf-8", errors="replace"):
            if line.startswith("# build "):
                build = line[len("# build "):].strip()
    if build:
        w(f"- **numj native build** (from the loaded DLL): `{build}`")
    if nenv:
        w(f"- **Python**: {nenv['python'].split()[0]}, **NumPy** {nenv['numpy']}")
        cfg = nenv.get("numpy_config", {})
        blas = cfg.get("Build Dependencies", {}).get("blas", {})
        if blas:
            w(f"- **NumPy BLAS**: {blas.get('name')} {blas.get('version', '')} ({blas.get('openblas configuration', '').strip()})")
        simd = cfg.get("SIMD Extensions", {})
        if simd:
            w(f"- **NumPy SIMD**: baseline {simd.get('baseline')}, dispatched {simd.get('found')}")
        w(f"- **Thread env for NumPy**: {nenv.get('thread_env')}")
    w("")

    # ---------------------------------------------------------------- data identity
    jf = {}
    fl = os.path.join(res, "java_fingerprints.log")
    if os.path.exists(fl):
        for line in open(fl):
            m = re.match(r"fingerprint (\S+) ([0-9a-f]+)", line.strip())
            if m:
                jf[m.group(1)] = m.group(2)
    pf = nenv.get("fingerprints", {})
    if jf and pf:
        same = all(jf.get(k) == v for k, v in pf.items()) and len(jf) == len(pf)
        w(f"**Input data identity:** Java and NumPy input fingerprints {'MATCH' if same else 'DIFFER'} "
          f"({len(pf)} datasets: {', '.join(f'{k}={v}' for k, v in pf.items())}).\n")

    # ---------------------------------------------------------------- main tables
    w("## Single-threaded comparison\n")
    w("All implementations single-threaded (NumPy BLAS forced to 1 thread), processes pinned to the P-cores. "
      "Cells: median per call (p10–p90 over 21 samples). Verdict columns: `X / numj` median ratio, then "
      "win/tie/lose by the non-overlap rule at the top of this file.\n")
    w("**compute** = inputs already in the implementation's own container, outputs preallocated where the API allows. "
      "**e2e** = numj starting from Java `double[]`: allocate native memory, copy in, compute, copy out, free. "
      "`numpy` (ordinary expressions) allocates its temporaries and result on every call, so it is end-to-end by nature.\n")

    kernels = [("sqdist", "Squared Euclidean distance `sum((a-b)**2)`"),
               ("sumsq_muladd", "Fused `sum((a*b + c)**2)`"),
               ("normalize_rows", "Row normalisation `x / ||x||` per row"),
               ("sqdist_rows", "Batched: squared distance from one query to every row")]
    for kname, title in kernels:
        shapes = []
        for r in rows:
            if r["kernel"] == kname and r["shape"] not in shapes:
                shapes.append(r["shape"])
        shapes.sort(key=lambda s: math.prod(int(x) for x in s.strip("[]").split(",")))
        if not shapes:
            continue
        w(f"### {title}\n")
        extra = kname == "sqdist_rows"
        hdr = ["shape", "numj compute", "numj e2e", "java-naive", "java-blocked", "numpy", "numpy-reuse"]
        if extra:
            hdr.insert(3, "numj per-row calls")
        hdr += ["vs numpy-reuse", "vs numpy", "vs java-naive", "vs java-blocked", "e2e: numpy / numj-e2e"]
        w("| " + " | ".join(hdr) + " |")
        w("|" + "---|" * len(hdr))
        for s in shapes:
            g = lambda impl, mode: idx.get((kname, s, impl, mode))
            nc, ne = g("numj", "compute"), g("numj", "e2e")
            cells = [s.replace(",", "×"), cell(nc), cell(ne)]
            if extra:
                cells.append(cell(g("numj-per-row-calls", "compute")))
            cells += [cell(g("java-naive", "compute")), cell(g("java-blocked", "compute")),
                      cell(g("numpy", "e2e")), cell(g("numpy-reuse", "compute")),
                      verdict(nc, g("numpy-reuse", "compute")), verdict(nc, g("numpy", "e2e")),
                      verdict(nc, g("java-naive", "compute")), verdict(nc, g("java-blocked", "compute")),
                      verdict(ne, g("numpy", "e2e"))]
            w("| " + " | ".join(cells) + " |")
        w("")

    # ---------------------------------------------------------------- agreement
    w("## Cross-implementation result agreement\n")
    w("Each benchmark records its last result (the scalar, or the last output element). Relative difference vs numj; "
      "the bound is `(depth_numj + depth_other + 3)·u` with naive/NumPy depth taken as n (a loose upper bound for NumPy's pairwise sum).\n")
    w("| kernel | shape | impl | value | rel. diff vs numj | within bound |")
    w("|---|---|---|---|---|---|")
    bad = 0
    for (k, s, impl, mode), r in sorted(idx.items()):
        if impl == "numj" or impl.startswith("numj-per") or mode == "e2e" and impl == "numj":
            continue
        ref = idx.get((k, s, "numj", "compute"))
        if not ref:
            continue
        a, b = r["result"], ref["result"]
        rel = abs(a - b) / abs(b) if b != 0 else abs(a - b)
        n = r["n"] if k in ("sqdist", "sumsq_muladd") else int(s.strip("[]").split(",")[-1])
        bound = (n + 4096 / 16 + 4 + 40 + 3) * U * (2 if k == "normalize_rows" else 1)
        ok = rel <= bound
        bad += not ok
        w(f"| {k} | {s} | {impl} | {a:.17g} | {rel:.2e} | {'yes' if ok else '**NO**'} |")
    w(f"\n{'All results agree within bounds.' if bad == 0 else f'{bad} results OUTSIDE bounds.'}\n")

    # ---------------------------------------------------------------- profiles
    prof = [r for p in glob.glob(os.path.join(res, "java_profile_*.csv")) for r in load(p)]
    if prof:
        w("## Vectorization / compiler-profile experiment (numj compute only)\n")
        w("Same Fortran source, different flags (see `scripts/build.ps1`). `numj` = AVX2 (x86-64-v3), strict FP; "
          "`sse2` = baseline x86-64 (128-bit vectors); `novec` = AVX2 target with auto-vectorization off; "
          "`fast` = `-ffast-math` (opt-in, relaxed semantics: fails the bitwise/overflow tests, see README). "
          "Ratios are `profile / numj` medians (> 1 = slower than the default).\n")
        profiles = ["numj", "numj-sse2", "numj-novec", "numj-fast"]
        pidx = {(r["kernel"], r["shape"], r["profile"]): r for r in prof}
        keys = []
        for r in prof:
            if (r["kernel"], r["shape"]) not in keys:
                keys.append((r["kernel"], r["shape"]))
        w("| kernel | shape | " + " | ".join(profiles) + " | sse2 / numj | novec / numj | fast / numj |")
        w("|---|---|" + "---|" * (len(profiles) + 3))
        for k, s in keys:
            base = pidx.get((k, s, "numj"))
            cs = [cell(pidx.get((k, s, p))) for p in profiles]
            rs = []
            for p in profiles[1:]:
                o = pidx.get((k, s, p))
                rs.append(f"{o['median_ns'] / base['median_ns']:.2f}" if o and base else "—")
            w(f"| {k} | {s.replace(',', '×')} | " + " | ".join(cs) + " | " + " | ".join(rs) + " |")
        w("")

    # ---------------------------------------------------------------- run-to-run
    if prof:
        w("## Run-to-run variability (same default build, two separate JVM runs)\n")
        w("The main suite and the profile suite both measure the default `numj` build in compute mode, in different "
          "processes a few minutes apart. Differences beyond the within-run p10–p90 show how much this laptop drifts "
          "between runs (power plan *Balanced*, thermal state). Treat single-run ratios within this drift as ties.\n")
        w("| kernel | shape | main run | profile run | profile / main |")
        w("|---|---|---|---|---|")
        drift = []
        for r in prof:
            if r["profile"] != "numj":
                continue
            m = idx.get((r["kernel"], r["shape"], "numj", "compute"))
            if not m:
                continue
            ratio = r["median_ns"] / m["median_ns"]
            drift.append(ratio)
            w(f"| {r['kernel']} | {r['shape'].replace(',', '×')} | {cell(m)} | {cell(r)} | {ratio:.2f} |")
        if drift:
            w(f"\nMedian-to-median drift between runs: {min(drift):.2f}× to {max(drift):.2f}×.\n")

    # ---------------------------------------------------------------- threads
    th = load(os.path.join(res, "java_threads.csv"))
    if th:
        w("## Optional native parallelism (numj compute only, OpenMP inside the DLL)\n")
        w("Same pinned P-core mask (4 cores / 8 hardware threads). Bandwidth = bytes the kernel must stream "
          "(sqdist 16 B/elem, sumsq_muladd 24 B/elem, normalize_rows 16 B/elem read+write) / median time. "
          "Results are bit-identical across thread counts (tested).\n")
        w("| kernel | shape | threads | median (p10–p90) | speedup vs 1 thread | GB/s |")
        w("|---|---|---|---|---|---|")
        bpe = {"sqdist": 16, "sumsq_muladd": 24, "normalize_rows": 16}
        base = {}
        for r in th:
            if r["threads"] == 1:
                base[(r["kernel"], r["shape"])] = r["median_ns"]
        for r in th:
            b = base.get((r["kernel"], r["shape"]))
            gbs = bpe[r["kernel"]] * r["n"] / r["median_ns"]
            w(f"| {r['kernel']} | {r['shape'].replace(',', '×')} | {r['threads']} | {cell(r)} | "
              f"{b / r['median_ns']:.2f}× | {gbs:.1f} |")
        w("")

    # ---------------------------------------------------------------- overhead
    oc = load(os.path.join(res, "java_overhead_critical.csv"))
    orr = load(os.path.join(res, "java_overhead_regular.csv"))
    if oc and orr:
        w("## Java→Fortran call overhead (sqdist on tiny inputs, full `NumJ.sqdist` path incl. validation)\n")
        w("| n | critical downcall | regular downcall | regular − critical |")
        w("|---|---|---|---|")
        ro = {r["n"]: r for r in orr}
        for r in oc:
            o = ro.get(r["n"])
            w(f"| {r['n']} | {cell(r)} | {cell(o)} | {t(o['median_ns'] - r['median_ns']) if o else '—'} |")
        w("")

    path = os.path.join(res, "RESULTS.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path)
    return 0 if bad == 0 else 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "results"))
