# Builds the native library (all profiles), the Java classes, tests, examples and (if the jars are present)
# the JMH benchmarks. Requires scripts/bootstrap.ps1 first.
#   build/native/numj.dll        strict  (default): -O3 -march=x86-64-v3 (AVX2), no FP contraction
#   build/native/numj-sse2.dll   strict semantics, baseline x86-64 (SSE2, 128-bit vectors)
#   build/native/numj-novec.dll  strict semantics, AVX2 target, auto-vectorization disabled
#   build/native/numj-fast.dll   OPT-IN relaxed FP: -ffast-math (FMA contraction, reassociation,
#                                reciprocal division, assumes no NaN/Inf). Not used unless selected.
# All DLLs are linked statically (libgfortran/libgomp/libgcc inside) so they depend only on Windows DLLs.
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'env.ps1')

$Common  = @('-std=f2018', '-Wall', '-Wextra', '-Wno-compare-reals', '-fopenmp', '-frecursive')
$Profiles = [ordered]@{
  'numj'       = @('-O3', '-march=x86-64-v3', '-ffp-contract=off')
  'numj-sse2'  = @('-O3', '-march=x86-64',    '-ffp-contract=off')
  'numj-novec' = @('-O3', '-march=x86-64-v3', '-ffp-contract=off', '-fno-tree-vectorize', '-fno-tree-slp-vectorize')
  'numj-fast'  = @('-O3', '-march=x86-64-v3', '-ffast-math')
}
# Module order matters (numj_reduce uses numj_kernels). numj_elementwise.f90 is generated by
# native/gen_elementwise.py and committed, so Python is not needed to build.
$Sources = @('numj_kernels', 'numj_elementwise', 'numj_reduce')

$Native = Join-Path $Root 'build\native'
New-Item -ItemType Directory -Force $Native | Out-Null
foreach ($name in $Profiles.Keys) {
  $obj = Join-Path $Root "build\obj\$name"
  New-Item -ItemType Directory -Force $obj | Out-Null
  $flags = $Common + $Profiles[$name]
  Write-Host "[fortran] $name : $($flags -join ' ')"
  $objs = @()
  foreach ($src in $Sources) {
    & gfortran @flags -J $obj -c (Join-Path $Root "native\$src.f90") -o "$obj\$src.o"
    if ($LASTEXITCODE -ne 0) { throw "gfortran compile failed ($name, $src)" }
    $objs += "$obj\$src.o"
  }
  & gfortran -shared -static -fopenmp -o "$Native\$name.dll" @objs
  if ($LASTEXITCODE -ne 0) { throw "gfortran link failed ($name)" }
}
# Vectorization reports for the default profile (kept for inspection): build/vec_<module>.txt
foreach ($src in $Sources) {
  & gfortran @Common @($Profiles['numj']) -J "$Root\build\obj\numj" "-fopt-info-vec-optimized=$Root\build\vec_$src.txt" -c (Join-Path $Root "native\$src.f90") -o "$Root\build\obj\numj\report_$src.o"
}

function Compile-Java([string]$out, [string[]]$srcDirs, [string]$cp) {
  $files = @(foreach ($d in $srcDirs) { Get-ChildItem -Recurse -Filter *.java (Join-Path $Root $d) | ForEach-Object FullName })
  New-Item -ItemType Directory -Force $out | Out-Null
  $jargs = @('--release', '25', '-Xlint:all', '-Werror', '-d', $out)
  if ($cp) { $jargs += @('-cp', $cp) }
  Write-Host "[javac] $out ($(@($files).Count) files)"
  & javac @jargs @files
  if ($LASTEXITCODE -ne 0) { throw "javac failed for $out" }
}
# Project-relative paths from here on (shorter, location-independent class paths).
Set-Location $Root
$Main = 'build\classes'
$Bench = 'build\bench-classes'
Compile-Java $Main @('java\src') $null
Compile-Java $Bench @('java\bench') $Main
Compile-Java 'build\test-classes' @('java\test') "$Main;$Bench"
Compile-Java 'build\example-classes' @('java\example') $Main

# JMH benchmarks: optional, needs the jars that bootstrap.ps1 fetches into .tools\jmh.
$JmhDir = '.tools\jmh'
if (Test-Path "$JmhDir\jmh-core-1.37.jar") {
  $JmhCp = (@(Get-ChildItem $JmhDir -Filter *.jar | ForEach-Object { "$JmhDir\$($_.Name)" })) -join ';'
  $files = @(Get-ChildItem -Recurse -Filter *.java 'java\jmh' | ForEach-Object FullName)
  New-Item -ItemType Directory -Force 'build\jmh-classes' | Out-Null
  Write-Host "[javac] build\jmh-classes ($(@($files).Count) files, JMH annotation processor)"
  & javac --release 25 -proc:full -cp "$Main;$Bench;$JmhCp" -d 'build\jmh-classes' @files
  if ($LASTEXITCODE -ne 0) { throw 'javac failed for the JMH benchmarks' }
} else {
  Write-Host '[skip] JMH jars not found in .tools\jmh (run scripts\bootstrap.ps1); JMH benchmarks not built'
}
Write-Host '[ok] build complete'
